const testimonials=[
	{id:"1",
		name:"John Doe",
		imageUrl:"http://placeimg.com/150/150/people",
		city:"Accra",
		country: "Ghana",
		testimony:"Lorem Ipsum is simply dummy text of theprinting and typesetting industry.Lorem Ipsum has been the industry's standard dummy text ever since the 1500s."
	},
	{id:"2",
		name:"Jane Elsa",
		imageUrl:"http://placeimg.com/350/350/tech",
		city:"Yaounde",
		country: "Cameroon",
		testimony:"It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."},
	{id:"3",
		name:"Helen Allie",
		imageUrl:"http://placeimg.com/150/150/nature",
		city:"Lagos",
		country: "Nigeria",
		testimony:"It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software"},
	{id:"4",
		name:"Jim Crow",
		imageUrl:"http://placeimg.com/150/150/architecture",
		city:"Kumasi",
		country: "Ghana",
		testimony:"It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout."},
	{id:"5",
		name:"Falone Evada",
		imageUrl:"http://placeimg.com/150/150",
		city:"Cape Town",
		country: "South Africa",
		testimony:"The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content', making it look like readable English."},
	{id:"6",
		name:"Fred Nerk",
		imageUrl:"http://placeimg.com/150/150/people",
		city:"Tamale",
		country: "Ghana",
		testimony:"Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."}
]

export default testimonials